version: "3.7"
services:
  ml_engine:
    build: ./ml_engine/
    volumes:
      - ./ml_engine:/work/ml_engine
    networks:
      - flownet
  tracking:
    build: ./mlflow_server/
    ports:
      - "5000:5000"
    expose:
      - "5001"
    networks:
      - flownet
    volumes:
      - ./mlruns:/mlruns

networks:
  flownet:
    driver: bridge
    