version: "3.7"
services:
  ml_engine:
    build: ./ml_engine/
    volumes:
      - ./ml_engine:/work/ml_engine
    networks:
      - flownet
    
  tracking:
    build: ./mlflow_server/
    ports:
      - "5000:5000"
    expose:
      - "5001"
    networks:
      - flownet
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri /mlruns --host 0.0.0.0 --port 5000

networks:
  flownet:
    driver: bridge
    